/*
 * Copyright 2016 Open Text.
 *
 * Licensed under the MIT License (the "License"); you may not use this file
 * except in compliance with the License.
 *
 * The only warranties for products and services of Open Text and its affiliates
 * and licensors ("Open Text") are as may be set forth in the express warranty
 * statements accompanying such products and services. Nothing herein should be
 * construed as constituting an additional warranty. Open Text shall not be
 * liable for technical or editorial errors or omissions contained herein. The
 * information contained herein is subject to change without notice.
 */

package com.opentext.idol.types.marshalling.marshallers;

import java.nio.charset.Charset;

/**
 * TO be implemented for classes which generate idol data
 *
 * @param <T> the type of document to generate
 */
@FunctionalInterface
public interface DocumentGenerator<T> {
    /**
     * Generates an xml document valid for indexing into Idol
     * The supplied documents are wrapped in a <Documents></Documents> root tag
     *
     * @param objects the documents to index
     * @param charset charset to use for converting generated bytes to String
     * @return the xml to send to Idol
     */
    String generateIdolXmlIndexDocument(final Iterable<T> objects, final Charset charset);
}
