/*
 * Copyright 2016 Hewlett Packard Enterprise Development Company, L.P.
 * Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
 */

package com.hp.autonomy.types.idol.marshalling.marshallers;

import java.nio.charset.Charset;

/**
 * TO be implemented for classes which generate idol data
 *
 * @param <T> the type of document to generate
 */
@FunctionalInterface
public interface DocumentGenerator<T> {
    /**
     * Generates an xml document valid for indexing into Idol
     * The supplied documents are wrapped in a <Documents></Documents> root tag
     *
     * @param objects the documents to index
     * @param charset charset to use for converting generated bytes to String
     * @return the xml to send to Idol
     */
    String generateIdolXmlIndexDocument(final Iterable<T> objects, final Charset charset);
}
